### ISSUE TITLE
VM size not available in East US region

### ISSUE THREAD

**Issue by rmontroy** [MicrosoftLearning/Configure-secure-access-to-workloads-with-Azure-virtual-networking-services#10]
#### 4. Deploy the virtual machines required for this exercise.
<code>PS /home/rob> $RGName = "RG1"
PS /home/rmontroy> New-AzResourceGroupDeployment -ResourceGroupName $RGName -TemplateUri https://raw.githubusercontent.com/MicrosoftLearning/Configure-secure-access-to-workloads-with-Azure-virtual-networking-services/main/Instructions/Labs/azuredeploy.json
New-AzResourceGroupDeployment: 5:45:11 PM - Error: Code=SkuNotAvailable; Message=The requested VM size for resource 'Following SKUs have failed for Capacity Restrictions: Standard_DS1_v2, Standard_DS1_v2' is currently not available in location 'eastus'. Please try another size or deploy to a different location or different zone. See https://aka.ms/azureskunotavailable for details.
New-AzResourceGroupDeployment: The deployment validation failed
</code>

Perhaps the template should have params for location and VM size.

**Comment by staleycyn** [comment]
Added a note to change the "location" value in the template if you receive a capacity restriction error.
