### ISSUE TITLE
Cannot specify relevant address range for AzureFirewallSubnet

### ISSUE THREAD

**Issue by nikmaxott** [MicrosoftLearning/Configure-secure-access-to-workloads-with-Azure-virtual-networking-services#7]
# Module: Configure secure access to workloads with Azure virtual networking services
#### Step: 5

Description of issue

AzureFirewallSubnet does not accept /24 

This also applies to 
Lab: Protect the web application from malicious traffic and block unauthorized access
Task:  Create Azure Firewall subnet in our existing virtual network
Step: 5

Repro steps:

1. Name the subnet `AzureFirewallSubnet`
1. You will get the error: `Please select 'Azure Firewall' in Subnet purpose dropdown to use the name 'AzureFirewallSubnet'.`
1. Select `Azure Firewall` in Subnet Purpose.
1. You cannot select a size, /26 by default

**Comment by jileary23** [comment]
Subnet has been updated to /26
