### ISSUE TITLE
Typo in "LAB_04_route.md" file

### ISSUE THREAD

**Issue by Rahul-1611** [MicrosoftLearning/Configure-secure-access-to-workloads-with-Azure-virtual-networking-services#8]
**Description** 
Subnet should specify "backend".
This typo is present in [[Instructions/Labs/LAB_04_route.md](https://github.com/MicrosoftLearning/Configure-secure-access-to-workloads-with-Azure-virtual-networking-services/blob/main/Instructions/Labs/LAB_04_route.md)](url)
<img width="543" alt="Screenshot 2024-11-12 at 20 41 15" src="https://github.com/user-attachments/assets/ad129a8c-075e-42c5-8a88-d64954b4cc29">

**Comment by Rahul-1611** [comment]
I guess this is a typo, if possible i can send a PR correcting it.

**Comment by remco-derooij** [comment]
@Rahul-1611  Same in LAB-02.
Diagram is showing app-frontend-asg with VM1, But instructions are referring to app-backend-asg
