### ISSUE TITLE
Unclear directions in LAB-02

### ISSUE THREAD

**Issue by remco-derooij** [MicrosoftLearning/Configure-secure-access-to-workloads-with-Azure-virtual-networking-services#9]
https://github.com/MicrosoftLearning/Configure-secure-access-to-workloads-with-Azure-virtual-networking-services/blob/main/Instructions/Labs/LAB_02_security_groups.md

Diagram is referring to app-frontend-asg

But instructions are referring to app-backend-asg

**Comment by staleycyn** [comment]
Made a correction.

**Comment by melvinporter** [comment]
Instructions are still referring to the non-existent app-backend-asg
